CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE,
    role_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES roles(id),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    last_login_at TIMESTAMP,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL REFERENCES users(id),
    name VARCHAR(100) NOT NULL,
    species VARCHAR(30) NOT NULL,
    breed VARCHAR(100),
    sex VARCHAR(10),
    birth_date DATE,
    weight_baseline_kg DECIMAL(5,2),
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE health_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    recorded_by_user_id BIGINT NOT NULL REFERENCES users(id),
    record_date DATE NOT NULL,
    weight_kg DECIMAL(5,2),
    meal_memo VARCHAR(300),
    exercise_minutes INTEGER,
    note TEXT,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE symptom_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    requested_by_user_id BIGINT NOT NULL REFERENCES users(id),
    symptom_type VARCHAR(100) NOT NULL,
    onset_text VARCHAR(100),
    memo VARCHAR(500),
    severity VARCHAR(10) NOT NULL CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH')),
    recommendation VARCHAR(10) NOT NULL CHECK (recommendation IN ('OBSERVE', 'CONSULT', 'VISIT')),
    ai_model VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    owner_user_id BIGINT NOT NULL REFERENCES users(id),
    staff_user_id BIGINT REFERENCES users(id),
    appointment_type VARCHAR(20) NOT NULL CHECK (appointment_type IN ('CONSULTATION', 'MEDICAL')),
    channel VARCHAR(20) NOT NULL CHECK (channel IN ('ONLINE', 'VISIT', 'HOSPITAL')),
    scheduled_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('REQUESTED', 'CONFIRMED', 'CANCELED', 'COMPLETED')),
    note VARCHAR(500),
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE medical_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    appointment_id BIGINT UNIQUE REFERENCES appointments(id),
    handled_by_user_id BIGINT NOT NULL REFERENCES users(id),
    performed_on DATE NOT NULL,
    treatment_detail VARCHAR(1000) NOT NULL,
    diagnosis VARCHAR(1000),
    prescription VARCHAR(1000),
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE medical_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medical_history_id BIGINT NOT NULL REFERENCES medical_histories(id),
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_mime_type VARCHAR(100) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    description VARCHAR(200),
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    monthly_fee DECIMAL(10,2) NOT NULL,
    features_json JSONB,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    plan_id BIGINT NOT NULL REFERENCES plans(id),
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'PAUSED', 'CANCELED')),
    auto_renew BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL REFERENCES subscriptions(id),
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    payment_status VARCHAR(20) NOT NULL CHECK (payment_status IN ('UNPAID', 'PARTIAL', 'PAID')),
    issued_at TIMESTAMP,
    paid_at TIMESTAMP,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id),
    paid_amount DECIMAL(10,2) NOT NULL,
    paid_at TIMESTAMP,
    payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('CARD', 'BANK', 'OTHER')),
    transaction_ref VARCHAR(100),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_type VARCHAR(20) NOT NULL CHECK (notification_type IN ('REMINDER', 'INFO', 'ALERT')),
    title VARCHAR(100) NOT NULL,
    body VARCHAR(2000) NOT NULL,
    scheduled_at TIMESTAMP,
    sent_at TIMESTAMP,
    delivery_status VARCHAR(20) NOT NULL CHECK (delivery_status IN ('DRAFT', 'SCHEDULED', 'SENT', 'FAILED')),
    created_by_user_id BIGINT NOT NULL REFERENCES users(id),
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notification_recipients (
    notification_id BIGINT NOT NULL REFERENCES notifications(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    read_at TIMESTAMP,
    delivery_status VARCHAR(20) NOT NULL CHECK (delivery_status IN ('PENDING', 'SENT', 'FAILED')),
    PRIMARY KEY (notification_id, user_id)
);

CREATE TABLE email_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(100) NOT NULL UNIQUE,
    subject_template VARCHAR(200) NOT NULL,
    body_template TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE email_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES email_templates(id),
    recipient_user_id BIGINT NOT NULL REFERENCES users(id),
    pet_id BIGINT REFERENCES pets(id),
    appointment_id BIGINT REFERENCES appointments(id),
    invoice_id BIGINT REFERENCES invoices(id),
    subject VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    send_timing_at TIMESTAMP,
    status VARCHAR(20) NOT NULL CHECK (status IN ('QUEUED', 'SENT', 'FAILED')),
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP
);

CREATE INDEX idx_users_role_id ON users(role_id);
CREATE INDEX idx_users_status_deleted_at ON users(status, deleted_at);

CREATE INDEX idx_pets_owner_user_id ON pets(owner_user_id);
CREATE INDEX idx_pets_species ON pets(species);

CREATE INDEX idx_health_records_pet_record_date ON health_records(pet_id, record_date);
CREATE INDEX idx_health_records_recorded_by_user_id ON health_records(recorded_by_user_id);

CREATE INDEX idx_symptom_checks_pet_created_at ON symptom_checks(pet_id, created_at);
CREATE INDEX idx_symptom_checks_requested_by_user_id ON symptom_checks(requested_by_user_id);

CREATE INDEX idx_appointments_pet_scheduled_at ON appointments(pet_id, scheduled_at);
CREATE INDEX idx_appointments_owner_scheduled_at ON appointments(owner_user_id, scheduled_at);
CREATE INDEX idx_appointments_staff_scheduled_at ON appointments(staff_user_id, scheduled_at);
CREATE INDEX idx_appointments_status_scheduled_at ON appointments(status, scheduled_at);

CREATE INDEX idx_medical_histories_pet_performed_on ON medical_histories(pet_id, performed_on);
CREATE INDEX idx_medical_attachments_history_id ON medical_attachments(medical_history_id);

CREATE INDEX idx_plans_is_active ON plans(is_active);

CREATE INDEX idx_subscriptions_user_status ON subscriptions(user_id, status);
CREATE INDEX idx_subscriptions_pet_status ON subscriptions(pet_id, status);
CREATE INDEX idx_subscriptions_plan_id ON subscriptions(plan_id);

CREATE INDEX idx_invoices_subscription_id ON invoices(subscription_id);
CREATE INDEX idx_invoices_payment_status_due_date ON invoices(payment_status, due_date);

CREATE INDEX idx_payments_invoice_id ON payments(invoice_id);
CREATE INDEX idx_payments_status ON payments(status);

CREATE INDEX idx_notifications_created_by ON notifications(created_by_user_id);
CREATE INDEX idx_notifications_status_scheduled ON notifications(delivery_status, scheduled_at);

CREATE INDEX idx_notification_recipients_user_status ON notification_recipients(user_id, delivery_status);

CREATE INDEX idx_email_messages_recipient_created ON email_messages(recipient_user_id, created_at);
CREATE INDEX idx_email_messages_status_send_timing ON email_messages(status, send_timing_at);
CREATE INDEX idx_email_messages_template_id ON email_messages(template_id);
