spring.application.name=petlife

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/petlifeplus}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:hs0512}
spring.datasource.driver-class-name=org.postgresql.Driver

# Initialize schema/data from classpath SQL
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Disable Hibernate DDL auto (MyBatis primary)
spring.jpa.hibernate.ddl-auto=none
